### ISSUE TITLE
Getting ValueError: Could not connect to a Chroma server. Are you sure it is running?

### ISSUE THREAD

**Issue by PrashantSaikia** [abhitatachar2000/dockerize-chromadb#5]
Here is the full trace of running `docker-compose up --build`:

```
[+] Building 0.6s (10/10) FINISHED                                                                             docker:desktop-linux
 => [application internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 182B                                                                                           0.0s
 => [application internal] load metadata for docker.io/library/python:latest                                                   0.5s
 => [application internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                                0.0s
 => [application 1/5] FROM docker.io/library/python:latest@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c66  0.0s
 => [application internal] load build context                                                                                  0.0s
 => => transferring context: 2.01kB                                                                                            0.0s
 => CACHED [application 2/5] WORKDIR /app                                                                                      0.0s
 => CACHED [application 3/5] COPY requirements.txt /app/                                                                       0.0s
 => CACHED [application 4/5] RUN pip install -r requirements.txt                                                               0.0s
 => CACHED [application 5/5] COPY . /app/                                                                                      0.0s
 => [application] exporting to image                                                                                           0.0s
 => => exporting layers                                                                                                        0.0s
 => => writing image sha256:a13b2923f9121bdb6b777d2436e62a1f3b2f0f6ccc5e74a9e229a276f212a025                                   0.0s
 => => naming to docker.io/library/application                                                                                 0.0s
[+] Running 1/1
 ✔ Container application  Created                                                                                              0.0s 
Attaching to application, chroma-1
chroma-1     | Starting 'uvicorn chromadb.app:app' with args: --workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30
application  | Traceback (most recent call last):
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
application  |     sock = connection.create_connection(
application  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
application  |     raise err
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
application  |     sock.connect(sa)
application  | ConnectionRefusedError: [Errno 111] Connection refused
application  | 
application  | The above exception was the direct cause of the following exception:
application  | 
application  | Traceback (most recent call last):
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
application  |     response = self._make_request(
application  |                ^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
application  |     conn.request(
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
application  |     self.endheaders()
application  |   File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
application  |     self._send_output(message_body, encode_chunked=encode_chunked)
application  |   File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
application  |     self.send(msg)
application  |   File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
application  |     self.connect()
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 238, in connect
application  |     self.sock = self._new_conn()
application  |                 ^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 213, in _new_conn
application  |     raise NewConnectionError(
application  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffffa396f440>: Failed to establish a new connection: [Errno 111] Connection refused
application  | 
application  | The above exception was the direct cause of the following exception:
application  | 
application  | Traceback (most recent call last):
application  |   File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 589, in send
application  |     resp = conn.urlopen(
application  |            ^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
application  |     retries = retries.increment(
application  |               ^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
application  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
application  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='chroma', port=8000): Max retries exceeded with url: /api/v1/tenants/default_tenant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa396f440>: Failed to establish a new connection: [Errno 111] Connection refused'))
application  | 
application  | During handling of the above exception, another exception occurred:
application  | 
application  | Traceback (most recent call last):
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/api/client.py", line 438, in _validate_tenant_database
application  |     self._admin_client.get_tenant(name=tenant)
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/api/client.py", line 486, in get_tenant
application  |     return self._server.get_tenant(name=name)
application  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
application  |     return f(*args, **kwargs)
application  |            ^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/api/fastapi.py", line 182, in get_tenant
application  |     resp = self._session.get(
application  |            ^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
application  |     return self.request("GET", url, **kwargs)
application  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
application  |     resp = self.send(prep, **send_kwargs)
application  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
application  |     r = adapter.send(request, **kwargs)
application  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 622, in send
application  |     raise ConnectionError(e, request=request)
application  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='chroma', port=8000): Max retries exceeded with url: /api/v1/tenants/default_tenant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa396f440>: Failed to establish a new connection: [Errno 111] Connection refused'))
application  | 
application  | During handling of the above exception, another exception occurred:
application  | 
application  | Traceback (most recent call last):
application  |   File "/app/chroma_client.py", line 4, in <module>
application  |     chroma_client = chromadb.HttpClient(host="chroma", port = 8000, settings=Settings(allow_reset=True, anonymized_telemetry=False))
application  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/__init__.py", line 197, in HttpClient
application  |     return ClientCreator(tenant=tenant, database=database, settings=settings)
application  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/api/client.py", line 144, in __init__
application  |     self._validate_tenant_database(tenant=tenant, database=database)
application  |   File "/usr/local/lib/python3.12/site-packages/chromadb/api/client.py", line 440, in _validate_tenant_database
application  |     raise ValueError(
application  | ValueError: Could not connect to a Chroma server. Are you sure it is running?
application exited with code 1
chroma-1     | WARNING:  [21-05-2024 20:29:15] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048576. chroma_server_nofile will not be set.
chroma-1     | INFO:     [21-05-2024 20:29:15] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component System
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component OpenTelemetryClient
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component SqliteDB
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component QuotaEnforcer
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component Posthog
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component LocalSegmentManager
chroma-1     | DEBUG:    [21-05-2024 20:29:15] Starting component SegmentAPI
chroma-1     | INFO:     [21-05-2024 20:29:15] Started server process [1]
chroma-1     | INFO:     [21-05-2024 20:29:15] Waiting for application startup.
chroma-1     | INFO:     [21-05-2024 20:29:15] Application startup complete.
chroma-1     | INFO:     [21-05-2024 20:29:15] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)


v View in Docker Desktop   w Enable Watch
```

**Comment by PrashantSaikia** [comment]
Using `chromadb==0.4.9` seems to fix this issue.
